/**
 * JavaScript visitor registry — maps every Babel AST node type
 * to its visitor function.
 *
 * Invariant 1: if an AST node type is encountered without a
 * registered visitor, walkFile() throws FATAL error.
 */
import type { VisitorRegistry } from './types.js';

// Declarations
import {
  visitVariableDeclaration,
  visitVariableDeclarator,
  visitFunctionDeclaration,
  visitClassDeclaration,
} from './visitors/declarations.js';

// Literals
import {
  visitStringLiteral,
  visitNumericLiteral,
  visitBooleanLiteral,
  visitNullLiteral,
  visitBigIntLiteral,
  visitRegExpLiteral,
  visitTemplateLiteral,
} from './visitors/literals.js';

// Expressions
import {
  visitCallExpression,
  visitMemberExpression,
  visitOptionalMemberExpression,
  visitOptionalCallExpression,
  visitAssignmentExpression,
  visitBinaryExpression,
  visitLogicalExpression,
  visitUnaryExpression,
  visitUpdateExpression,
  visitNewExpression,
  visitArrowFunctionExpression,
  visitFunctionExpression,
  visitConditionalExpression,
  visitAwaitExpression,
  visitYieldExpression,
  visitSpreadElement,
  visitIdentifier,
  visitThisExpression,
  visitSequenceExpression,
  visitParenthesizedExpression,
  visitTaggedTemplateExpression,
  visitClassExpression,
  visitObjectExpression,
  visitArrayExpression,
  visitObjectProperty,
  visitObjectMethod,
} from './visitors/expressions.js';

// Statements
import {
  visitIfStatement,
  visitForStatement,
  visitForInStatement,
  visitForOfStatement,
  visitWhileStatement,
  visitDoWhileStatement,
  visitSwitchStatement,
  visitSwitchCase,
  visitTryStatement,
  visitCatchClause,
  visitReturnStatement,
  visitThrowStatement,
  visitBlockStatement,
  visitExpressionStatement,
  visitEmptyStatement,
  visitDebuggerStatement,
  visitBreakStatement,
  visitContinueStatement,
  visitLabeledStatement,
  visitWithStatement,
} from './visitors/statements.js';

// Modules
import {
  visitImportDeclaration,
  visitExportNamedDeclaration,
  visitExportDefaultDeclaration,
  visitExportAllDeclaration,
  visitImportSpecifier,
  visitImportDefaultSpecifier,
  visitImportNamespaceSpecifier,
  visitExportSpecifier,
} from './visitors/modules.js';

// Classes
import {
  visitClassBody,
  visitClassMethod,
  visitClassProperty,
  visitClassPrivateMethod,
  visitClassPrivateProperty,
  visitStaticBlock,
  visitClassAccessorProperty,
} from './visitors/classes.js';

// TypeScript
import {
  visitTSInterfaceDeclaration,
  visitTSTypeAliasDeclaration,
  visitTSEnumDeclaration,
  visitTSEnumMember,
  visitTSModuleDeclaration,
  visitTSTypeAnnotation,
  visitTSTypeReference,
  visitTSQualifiedName,
  visitTSTypeParameterInstantiation,
  visitTSTypeParameterDeclaration,
  visitTSTypeParameter,
  visitTSFunctionType,
  visitTSConstructSignatureDeclaration,
  visitTSCallSignatureDeclaration,
  visitTSPropertySignature,
  visitTSMethodSignature,
  visitTSIndexSignature,
  visitTSTypePredicate,
  visitTSTypeOperator,
  visitTSIndexedAccessType,
  visitTSMappedType,
  visitTSLiteralType,
  visitTSExpressionWithTypeArguments,
  visitTSInterfaceBody,
  visitTSConditionalType,
  visitTSInferType,
  visitTSParenthesizedType,
  visitTSUnionType,
  visitTSIntersectionType,
  visitTSArrayType,
  visitTSTupleType,
  visitTSOptionalType,
  visitTSRestType,
  visitTSNamedTupleMember,
  visitTSTemplateLiteralType,
  visitTSAnyKeyword,
  visitTSBooleanKeyword,
  visitTSBigIntKeyword,
  visitTSIntrinsicKeyword,
  visitTSNeverKeyword,
  visitTSNullKeyword,
  visitTSNumberKeyword,
  visitTSObjectKeyword,
  visitTSStringKeyword,
  visitTSSymbolKeyword,
  visitTSUndefinedKeyword,
  visitTSUnknownKeyword,
  visitTSVoidKeyword,
  visitTSThisType,
  visitTSTypeQuery,
  visitTSTypeLiteral,
  visitTSAsExpression,
  visitTSSatisfiesExpression,
  visitTSTypeAssertion,
  visitTSNonNullExpression,
  visitTSInstantiationExpression,
  visitTSImportType,
  visitTSExternalModuleReference,
  visitTSModuleBlock,
  visitTSImportEqualsDeclaration,
  visitTSExportAssignment,
  visitTSNamespaceExportDeclaration,
  visitTSDeclareFunction,
  visitTSDeclareMethod,
  visitTSTemplateParameterInstantiation,
  visitTSParameterProperty,
  visitTSConstructorType,
} from './visitors/typescript.js';

// Misc
import {
  visitObjectPattern,
  visitArrayPattern,
  visitRestElement,
  visitAssignmentPattern,
  visitTemplateElement,
  visitJSXElement,
  visitJSXFragment,
  visitJSXOpeningElement,
  visitJSXClosingElement,
  visitJSXOpeningFragment,
  visitJSXClosingFragment,
  visitJSXAttribute,
  visitJSXSpreadAttribute,
  visitJSXText,
  visitJSXExpressionContainer,
  visitJSXSpreadChild,
  visitJSXEmptyExpression,
  visitJSXIdentifier,
  visitJSXMemberExpression,
  visitJSXNamespacedName,
  visitDirective,
  visitDirectiveLiteral,
  visitFile,
  visitProgram,
  visitInterpreterDirective,
  visitMetaProperty,
  visitSuper,
  visitPrivateName,
  visitV8IntrinsicIdentifier,
  visitArgumentPlaceholder,
  visitDecorator,
  visitImport,
  visitExportNamespaceSpecifier,
  visitExportDefaultSpecifier,
} from './visitors/misc.js';

/**
 * Complete JavaScript/TypeScript visitor registry.
 */
export const jsRegistry: VisitorRegistry = {
  // Declarations
  VariableDeclaration: visitVariableDeclaration,
  VariableDeclarator: visitVariableDeclarator,
  FunctionDeclaration: visitFunctionDeclaration,
  ClassDeclaration: visitClassDeclaration,

  // Literals
  StringLiteral: visitStringLiteral,
  NumericLiteral: visitNumericLiteral,
  BooleanLiteral: visitBooleanLiteral,
  NullLiteral: visitNullLiteral,
  BigIntLiteral: visitBigIntLiteral,
  RegExpLiteral: visitRegExpLiteral,
  TemplateLiteral: visitTemplateLiteral,

  // Expressions
  CallExpression: visitCallExpression,
  MemberExpression: visitMemberExpression,
  OptionalMemberExpression: visitOptionalMemberExpression,
  OptionalCallExpression: visitOptionalCallExpression,
  AssignmentExpression: visitAssignmentExpression,
  BinaryExpression: visitBinaryExpression,
  LogicalExpression: visitLogicalExpression,
  UnaryExpression: visitUnaryExpression,
  UpdateExpression: visitUpdateExpression,
  NewExpression: visitNewExpression,
  ArrowFunctionExpression: visitArrowFunctionExpression,
  FunctionExpression: visitFunctionExpression,
  ConditionalExpression: visitConditionalExpression,
  AwaitExpression: visitAwaitExpression,
  YieldExpression: visitYieldExpression,
  SpreadElement: visitSpreadElement,
  Identifier: visitIdentifier,
  ThisExpression: visitThisExpression,
  SequenceExpression: visitSequenceExpression,
  ParenthesizedExpression: visitParenthesizedExpression,
  TaggedTemplateExpression: visitTaggedTemplateExpression,
  ClassExpression: visitClassExpression,
  ObjectExpression: visitObjectExpression,
  ArrayExpression: visitArrayExpression,
  ObjectProperty: visitObjectProperty,
  ObjectMethod: visitObjectMethod,

  // Statements
  IfStatement: visitIfStatement,
  ForStatement: visitForStatement,
  ForInStatement: visitForInStatement,
  ForOfStatement: visitForOfStatement,
  WhileStatement: visitWhileStatement,
  DoWhileStatement: visitDoWhileStatement,
  SwitchStatement: visitSwitchStatement,
  SwitchCase: visitSwitchCase,
  TryStatement: visitTryStatement,
  CatchClause: visitCatchClause,
  ReturnStatement: visitReturnStatement,
  ThrowStatement: visitThrowStatement,
  BlockStatement: visitBlockStatement,
  ExpressionStatement: visitExpressionStatement,
  EmptyStatement: visitEmptyStatement,
  DebuggerStatement: visitDebuggerStatement,
  BreakStatement: visitBreakStatement,
  ContinueStatement: visitContinueStatement,
  LabeledStatement: visitLabeledStatement,
  WithStatement: visitWithStatement,

  // Modules
  ImportDeclaration: visitImportDeclaration,
  ExportNamedDeclaration: visitExportNamedDeclaration,
  ExportDefaultDeclaration: visitExportDefaultDeclaration,
  ExportAllDeclaration: visitExportAllDeclaration,
  ImportSpecifier: visitImportSpecifier,
  ImportDefaultSpecifier: visitImportDefaultSpecifier,
  ImportNamespaceSpecifier: visitImportNamespaceSpecifier,
  ExportSpecifier: visitExportSpecifier,
  ExportNamespaceSpecifier: visitExportNamespaceSpecifier,
  ExportDefaultSpecifier: visitExportDefaultSpecifier,

  // Classes
  ClassBody: visitClassBody,
  ClassMethod: visitClassMethod,
  ClassProperty: visitClassProperty,
  ClassPrivateMethod: visitClassPrivateMethod,
  ClassPrivateProperty: visitClassPrivateProperty,
  StaticBlock: visitStaticBlock,
  ClassAccessorProperty: visitClassAccessorProperty,

  // TypeScript
  TSInterfaceDeclaration: visitTSInterfaceDeclaration,
  TSTypeAliasDeclaration: visitTSTypeAliasDeclaration,
  TSEnumDeclaration: visitTSEnumDeclaration,
  TSEnumMember: visitTSEnumMember,
  TSModuleDeclaration: visitTSModuleDeclaration,
  TSTypeAnnotation: visitTSTypeAnnotation,
  TSTypeReference: visitTSTypeReference,
  TSQualifiedName: visitTSQualifiedName,
  TSTypeParameterInstantiation: visitTSTypeParameterInstantiation,
  TSTypeParameterDeclaration: visitTSTypeParameterDeclaration,
  TSTypeParameter: visitTSTypeParameter,
  TSFunctionType: visitTSFunctionType,
  TSConstructSignatureDeclaration: visitTSConstructSignatureDeclaration,
  TSCallSignatureDeclaration: visitTSCallSignatureDeclaration,
  TSPropertySignature: visitTSPropertySignature,
  TSMethodSignature: visitTSMethodSignature,
  TSIndexSignature: visitTSIndexSignature,
  TSTypePredicate: visitTSTypePredicate,
  TSTypeOperator: visitTSTypeOperator,
  TSIndexedAccessType: visitTSIndexedAccessType,
  TSMappedType: visitTSMappedType,
  TSLiteralType: visitTSLiteralType,
  TSExpressionWithTypeArguments: visitTSExpressionWithTypeArguments,
  TSInterfaceBody: visitTSInterfaceBody,
  TSConditionalType: visitTSConditionalType,
  TSInferType: visitTSInferType,
  TSParenthesizedType: visitTSParenthesizedType,
  TSUnionType: visitTSUnionType,
  TSIntersectionType: visitTSIntersectionType,
  TSArrayType: visitTSArrayType,
  TSTupleType: visitTSTupleType,
  TSOptionalType: visitTSOptionalType,
  TSRestType: visitTSRestType,
  TSNamedTupleMember: visitTSNamedTupleMember,
  TSTemplateLiteralType: visitTSTemplateLiteralType,
  TSAnyKeyword: visitTSAnyKeyword,
  TSBooleanKeyword: visitTSBooleanKeyword,
  TSBigIntKeyword: visitTSBigIntKeyword,
  TSIntrinsicKeyword: visitTSIntrinsicKeyword,
  TSNeverKeyword: visitTSNeverKeyword,
  TSNullKeyword: visitTSNullKeyword,
  TSNumberKeyword: visitTSNumberKeyword,
  TSObjectKeyword: visitTSObjectKeyword,
  TSStringKeyword: visitTSStringKeyword,
  TSSymbolKeyword: visitTSSymbolKeyword,
  TSUndefinedKeyword: visitTSUndefinedKeyword,
  TSUnknownKeyword: visitTSUnknownKeyword,
  TSVoidKeyword: visitTSVoidKeyword,
  TSThisType: visitTSThisType,
  TSTypeQuery: visitTSTypeQuery,
  TSTypeLiteral: visitTSTypeLiteral,
  TSAsExpression: visitTSAsExpression,
  TSSatisfiesExpression: visitTSSatisfiesExpression,
  TSTypeAssertion: visitTSTypeAssertion,
  TSNonNullExpression: visitTSNonNullExpression,
  TSInstantiationExpression: visitTSInstantiationExpression,
  TSImportType: visitTSImportType,
  TSExternalModuleReference: visitTSExternalModuleReference,
  TSModuleBlock: visitTSModuleBlock,
  TSImportEqualsDeclaration: visitTSImportEqualsDeclaration,
  TSExportAssignment: visitTSExportAssignment,
  TSNamespaceExportDeclaration: visitTSNamespaceExportDeclaration,
  TSDeclareFunction: visitTSDeclareFunction,
  TSDeclareMethod: visitTSDeclareMethod,
  TSParameterProperty: visitTSParameterProperty,
  TSConstructorType: visitTSConstructorType,
  TSTemplateParameterInstantiation: visitTSTemplateParameterInstantiation,

  // Misc
  ObjectPattern: visitObjectPattern,
  ArrayPattern: visitArrayPattern,
  RestElement: visitRestElement,
  AssignmentPattern: visitAssignmentPattern,
  TemplateElement: visitTemplateElement,
  Directive: visitDirective,
  DirectiveLiteral: visitDirectiveLiteral,
  File: visitFile,
  Program: visitProgram,
  InterpreterDirective: visitInterpreterDirective,
  MetaProperty: visitMetaProperty,
  Super: visitSuper,
  PrivateName: visitPrivateName,
  V8IntrinsicIdentifier: visitV8IntrinsicIdentifier,
  ArgumentPlaceholder: visitArgumentPlaceholder,
  Decorator: visitDecorator,
  Import: visitImport,

  // JSX
  JSXElement: visitJSXElement,
  JSXFragment: visitJSXFragment,
  JSXOpeningElement: visitJSXOpeningElement,
  JSXClosingElement: visitJSXClosingElement,
  JSXOpeningFragment: visitJSXOpeningFragment,
  JSXClosingFragment: visitJSXClosingFragment,
  JSXAttribute: visitJSXAttribute,
  JSXSpreadAttribute: visitJSXSpreadAttribute,
  JSXText: visitJSXText,
  JSXExpressionContainer: visitJSXExpressionContainer,
  JSXSpreadChild: visitJSXSpreadChild,
  JSXEmptyExpression: visitJSXEmptyExpression,
  JSXIdentifier: visitJSXIdentifier,
  JSXMemberExpression: visitJSXMemberExpression,
  JSXNamespacedName: visitJSXNamespacedName,
};
