/**
 * ReactNode - contract for React domain-specific nodes
 *
 * Handles all namespaced types from ReactAnalyzer:
 * - react:component, react:state, react:effect, react:layout-effect,
 *   react:insertion-effect, react:callback, react:memo, react:ref,
 *   react:reducer, react:context, react:context-use, react:imperative-handle
 * - dom:event
 * - browser:timer, browser:blocking, browser:async, browser:storage,
 *   browser:dom, browser:history, browser:clipboard, browser:geolocation,
 *   browser:media-query
 * - canvas:draw
 *
 * Issue nodes (issue:stale-closure, issue:missing-cleanup, issue:raf-leak)
 * are handled by the existing IssueNode contract.
 *
 * These nodes use domain-specific ID formats generated by the analyzer
 * helpers (react-internal/), so the contract provides a generic create()
 * that validates required fields and brands the node.
 */

import type { BaseNodeRecord } from '@grafema/types';
import { getNamespace } from './NodeKind.js';

export interface ReactNodeRecord extends BaseNodeRecord {
  type: string;
  [key: string]: unknown;
}

const REACT_NAMESPACES = ['react', 'dom', 'browser', 'canvas'] as const;

export class ReactNode {
  static readonly REQUIRED = ['id', 'type', 'file', 'line'] as const;

  /**
   * Create a React domain node from pre-built fields.
   *
   * The analyzers' helper modules (react-internal/) build the full node
   * shape including ID. This method validates required fields and returns
   * a properly typed record ready for branding.
   *
   * @param fields - Complete node fields including id, type, file, line
   * @returns ReactNodeRecord ready for brandNodeInternal()
   */
  static create<T extends { id: string; type: string; file: string; line: number }>(fields: T): ReactNodeRecord {
    if (!fields.id) throw new Error('ReactNode.create: id is required');
    if (!fields.type) throw new Error('ReactNode.create: type is required');
    if (!fields.file) throw new Error('ReactNode.create: file is required');
    if (fields.line === undefined) throw new Error('ReactNode.create: line is required');

    return fields as unknown as ReactNodeRecord;
  }

  /**
   * Validate a React domain node.
   */
  static validate(node: BaseNodeRecord): string[] {
    const errors: string[] = [];

    if (!ReactNode.isReactDomainType(node.type)) {
      errors.push(`Expected react/dom/browser/canvas type, got ${node.type}`);
    }

    if (!node.id) errors.push('Missing required field: id');
    if (!node.file) errors.push('Missing required field: file');

    return errors;
  }

  /**
   * Check if a type belongs to the React domain.
   */
  static isReactDomainType(type: string): boolean {
    if (!type) return false;
    const ns = getNamespace(type);
    return ns !== null && (REACT_NAMESPACES as readonly string[]).includes(ns);
  }
}
